"""empty message

Revision ID: 4695405f7fd2
Revises: 0018d54ca70e
Create Date: 2021-06-09 23:15:51.775994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4695405f7fd2'
down_revision = '0018d54ca70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chore_list', ['chore_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
