"""empty message

Revision ID: 7404091f3331
Revises: 8116071a594b
Create Date: 2021-06-09 23:51:07.317307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7404091f3331'
down_revision = '8116071a594b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_progress', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
