"""empty message

Revision ID: 8116071a594b
Revises: 4695405f7fd2
Create Date: 2021-06-09 23:22:13.358776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8116071a594b'
down_revision = '4695405f7fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_chore_assignments_chore_id_chore_list'), 'chore_list', ['chore_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chore_assignments_chore_id_chore_list'), type_='foreignkey')

    # ### end Alembic commands ###
