"""empty message

Revision ID: ba8940b615a3
Revises: b076918a05c0
Create Date: 2021-05-13 11:30:11.892288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8940b615a3'
down_revision = 'b076918a05c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_list', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
