"""empty message

Revision ID: e391f6ec145b
Revises: ba8940b615a3
Create Date: 2021-05-26 15:59:33.665781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e391f6ec145b'
down_revision = 'ba8940b615a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.drop_column('assigned_by_id')

    # ### end Alembic commands ###
